In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])

In [5]:
a

array([1, 2, 3])

In [7]:
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype=float)

In [9]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [11]:
c = np.array([[(1.5, 2, 3), (4, 5, 6)], [(3, 2, 1), (4, 5, 6)]], dtype=float)

In [13]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [17]:
p=np.zeros([3, 4])

In [19]:
p

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
p=np.ones(([2, 3, 4]), dtype=np.int16)

In [23]:
p

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [25]:
p=np.arange(10, 25, 5)

In [27]:
p

array([10, 15, 20])

In [29]:
p=np.linspace(0, 2, 9)

In [31]:
p

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [33]:
p=np.full((2, 2), 7)

In [35]:
p

array([[7, 7],
       [7, 7]])

In [43]:
p=np.eye(2)
p_r=np.random.random((2, 2))
print("Identity Matrix:\n", p)
print("Random Matrix:\n", p_r)

Identity Matrix:
 [[1. 0.]
 [0. 1.]]
Random Matrix:
 [[0.2219361  0.90486864]
 [0.26767829 0.34123399]]


In [45]:
for name, arr in [('a', a), ('b', b), ('c', c)]:
    print(f"Array {name}: Shape={arr.shape}, Ndim={arr.ndim}, Size={arr.size}")

Array a: Shape=(3,), Ndim=1, Size=3
Array b: Shape=(2, 3), Ndim=2, Size=6
Array c: Shape=(2, 2, 3), Ndim=3, Size=12


In [47]:
print(f"b dtype: {b.dtype}, name: {b.dtype.name}")
b_int = b.astype(int)

b dtype: float64, name: float64


In [62]:
add_res = a + b
sub_res = a - b
print("\nAddition (a + b):")
print(add_res)

print("\nSubtraction (a - b):")
print(sub_res)


Addition (a + b):
[[2.5 4.  6. ]
 [5.  7.  9. ]]

Subtraction (a - b):
[[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]


In [64]:
mul_res = b * b
div_res = b / b
print("\nElement-wise Multiplication (b * b):")
print(mul_res)

print("\nElement-wise Division (b / b):")
print(div_res)


Element-wise Multiplication (b * b):
[[ 2.25  4.    9.  ]
 [16.   25.   36.  ]]

Element-wise Division (b / b):
[[1. 1. 1.]
 [1. 1. 1.]]


In [66]:
sqrt_res = np.sqrt(b)
print("Array b:")
print(b)

print("\nSquare Root of Array b (sqrt_res):")
print(sqrt_res)

Array b:
[[1.5 2.  3. ]
 [4.  5.  6. ]]

Square Root of Array b (sqrt_res):
[[1.22474487 1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [58]:
print(f"Sum: {b.sum()}")
print(f"Min: {b.min()}")
print(f"Max: {b.max()}")
print(f"Cumsum: {b.cumsum()}")
print(f"Mean: {np.mean(b)}")
print(f"Median: {np.median(b)}")
print(f"Std Dev: {np.std(b)}")

Sum: 21.5
Min: 1.5
Max: 6.0
Cumsum: [ 1.5  3.5  6.5 10.5 15.5 21.5]
Mean: 3.5833333333333335
Median: 3.5
Std Dev: 1.5920810978785667
